### ISSUE TITLE
use of draw_score and draw_gtscore function in models/__init__.py

### ISSUE THREAD

**Issue by sggodboy** [sylvainma/Summarizer#20]
I really appreciate your effort in creating this repository.
Can you please specify the usage of draw_score and draw_gtscore functions. Where these functions are called.

**Comment by sylvainma** [comment]
Hi @sggodboy !

Theses functions actually write Tensorboard logs. The logs path is specified in the config file here:
https://github.com/sylvainma/Summarizer/blob/b0a884ef70b7a56420ae31954cb87c1a4b074e0a/summarizer/utils/config.py#L91

When the models are trained and even after, you can start tensorboard in this log directory.
